services:
  web:
    image: karakeep/web:${KARAKEEP_WEB_TAG:-local}
    build:
      dockerfile: docker/Dockerfile
      context: ..
      target: aio
      args:
        SERVER_VERSION: ${KARAKEEP_VERSION:-release}
        DEBIAN_APT_MIRROR: ${DEBIAN_APT_MIRROR:-http://mirrors.aliyun.com/debian}
        DEBIAN_SECURITY_APT_MIRROR: ${DEBIAN_SECURITY_APT_MIRROR:-http://mirrors.aliyun.com/debian-security}
        NPM_REGISTRY: ${NPM_REGISTRY:-https://registry.npmmirror.com/}
        CARGO_REGISTRIES_CRATES_IO_INDEX: ${CARGO_REGISTRIES_CRATES_IO_INDEX:-https://rsproxy.cn/crates.io-index}
        CARGO_REGISTRIES_CRATES_IO_PROTOCOL: ${CARGO_REGISTRIES_CRATES_IO_PROTOCOL:-sparse}
    restart: unless-stopped
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - data:/data
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...

      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS
  chrome:
    image: karakeep/chrome-desktop:${KARAKEEP_CHROME_TAG:-local}
    build:
      context: ./chrome-desktop
      args:
        UBUNTU_APT_MIRROR: ${UBUNTU_APT_MIRROR:-http://mirrors.aliyun.com/ubuntu/}
    restart: unless-stopped
    shm_size: 1gb
    cap_add:
      - SYS_ADMIN
    ports:
      - "${KARAKEEP_CHROME_DESKTOP_PORT:-127.0.0.1:6080:6080}"
      - "${KARAKEEP_CHROME_DEBUG_PORT:-127.0.0.1:9222:9222}"
    environment:
      CHROME_REMOTE_DEBUGGING_PORT: 9222
      CHROME_PROXY_SERVER: ${CHROME_PROXY_SERVER:-}
      CHROME_PROXY_BYPASS_LIST: ${CHROME_PROXY_BYPASS_LIST:-}
      CHROME_PROXY_PAC_URL: ${CHROME_PROXY_PAC_URL:-}
      CHROME_DISABLE_SANDBOX: ${CHROME_DISABLE_SANDBOX:-false}
  meilisearch:
    image: getmeili/meilisearch:v1.37.0
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

volumes:
  meilisearch:
  data:




